---
# tasks file for db
- name: Change mongo config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongod
  
# handlers file for db
- name: restart mongod
  service:
    name: mongod
    state: restarted

- name: Sho info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"
